config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "rooms#index"
  get 'search/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: { sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks",
                            passwords: "users/passwords", registrations: "users/registrations", confirmations: "users/confirmations", mailer: "users/mailer", unlocks: "users/unlocks" }
  resources :rooms do
    delete "/photos/:photo_id" => "rooms#destroy_photo", as: :destroy_photo, on: :member
    collection do
      get "manage"
      get "wish_list_rooms"
    end
    member do
      patch :wish_list
    end
  end

  resources :bookings, only: %i[create show new index]  do
    member do
      get "confirm"
      get "cancel"
      post "create_review"
    end
      collection do
      get 'ebpay'
      post 'ebpaid'
    end
  end
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  before_validation :generate_serial
  belongs_to :user
  belongs_to :room
  has_many :reviews
  

  validates :price_per_night, presence: true
  validates :start_at, :end_at, presence: true
  validate :end_date_after_start_date, :other_booking_during_the_period

  scope :paid, -> { where(state: "paid") }
  scope :not_due, -> { where("end_at >= ?",Time.current) }

  enum state: %i[pending unpaid paid cancelled past]


  private

  def generate_serial
    self.serial = SecureRandom.alphanumeric(13)
  end

  def paid
    scope :state, -> { where state: 2 }
  end

  def past
    scope :state, -> { where state: 4 }
  end

  def cancelled
    scope :state, -> { where state: 3 }
  end

  def end_date_after_start_date
    return if end_at.blank? || start_at.blank?

    errors.add(:end_at, 'must be after the start date') if end_at < start_at
  end

  def other_booking_during_the_period
    return unless disable_dates(Room.find(room_id)).intersect?((start_at..(end_at - 1)).to_a)

    errors.add(:end_at, 'already booked by someone else')
  end

  def disable_dates(room)
    disabledates = []
    room.bookings.paid.map do |booking|
      (booking.start_at..booking.end_at.yesterday).map do |disabledate|
        disabledates << disabledate
      end
      disabledates.flatten
    end
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[index confirm cancel ebpaid notify_response]
  skip_before_action :authenticate_user!, only: %i[confirm cancel ebpaid]
  before_action :should_compelete_user_info, only: [:new]
  before_action :cancel_unpaid_bookings, :update_past_bookings
  protect_from_forgery with: :null_session, only: [:ebpaid]

  def create
    @room = Room.find(params[:booking][:room_id])
    @booking = Booking.new(booking_params)
    
    if @booking.save
      @booking.unpaid!
      # after payment success => get the response from the confirm api
      @api_obj = LinePayApi.new('/v3/payments/request')

      req_nonce = @api_obj.nonce
      req_body = @api_obj.req_body(@room, @booking)
      req_signature = @api_obj.get_signature(req_nonce, req_body)
      req_header = @api_obj.header(req_nonce, req_signature)

      # get the response from the request api => get the paymentUrl
      req_response = @api_obj.get_response(req_header, req_body)

      # redirect to the paymentUrl => user scans and pays
      if device() == 'desktop'
        webConfirmUrl = JSON.parse(req_response.body)['info']['paymentUrl']['web']
        redirect_to webConfirmUrl
      else
        appConfirmUrl = JSON.parse(req_response.body)['info']['paymentUrl']['app']
        redirect_to appConfirmUrl
      end
      # if payment success => redirect to the confirmUrl
      # if not => redirect to the cancelUrl
    else
      redirect_to room_path(@room), alert: '訂房失敗'
    end
  end

  def confirm
    @booking = Booking.find_by!(serial: params[:id])
    return unless @booking.paid!

    @api_obj = LinePayApi.new("/v3/payments/#{params[:transactionId]}/confirm")
    confirm_nonce = @api_obj.nonce
    confirm_body = @api_obj.confirm_body(@booking)
    confirm_signature = @api_obj.get_signature(confirm_nonce, confirm_body)
    @api_obj.get_response(@api_obj.header(confirm_nonce, confirm_signature), confirm_body)

    if device() == 'desktop'
      redirect_to root_path, notice: '訂單付款成功'
    end
  end

  def index
    @first_booking = current_user.bookings.paid.order(start_at: :ASC).first
    @past_bookings = current_user.bookings.past
    @cancelled_bookings = current_user.bookings.cancelled
  end

  def new  
    @booking = current_user.bookings.new
    @room = Room.find(params[:room_id])
    @owner_name = User.find(@room.user_id).name || '房東'
    @room_intro = @room.summary.size >= 15 ? @room.summary[0..15] : @room.summary
    @nights = (params[:end_at].to_date - params[:start_at].to_date).to_i
  end

  def ebpay
    @nights = (params[:end_at].to_date - params[:start_at].to_date).to_i
    @ebroom = Room.find(params[:room_id])
    @ebbooking = Booking.new({
      user_id: current_user.id,
      room_id: params[:room_id],
      price_per_night: @ebroom.price * @nights,
      start_at: params[:start_at],
      end_at: params[:end_at],
      headcount: params[:headcount]
    })

    if @ebbooking.save
      @ebbooking.unpaid!
      mpg = Newebpay::Mpg.new(@ebbooking, @ebroom, @nights)
      @form_info = mpg.form_info
      @info = mpg.info

      render json: { data: @ebbooking, form_info: @form_info, info: @info}
    end
  end

  def ebpaid
    response = Newebpay::MpgResponse.new(params[:TradeInfo])
    @ebbooking = Booking.find_by(serial: response.order_no)
    @ebbooking.paid!
    
    redirect_to root_path, notice: '訂單付款成功'
    flash.keep(:notice)
  end
  

  def show
    @booking = Booking.find(params[:id])
    @review = Review.new
    @room_review = @booking.reviews.where(review_to: 'room')
    @nights = (@booking.end_at.to_date - @booking.start_at.to_date).to_i
  end

  def cancel
    @booking = Booking.find(params[:id])
    @booking.update_column(:state, 3)
    @booking.cancelled!
    if @booking.paid?
      redirect_to room_path, notice: '成功取消預訂'
    else
      redirect_to root_path, notice: '訂單付款失敗'
    end
  end

  def create_review
    @review = Review.create!(review_params)
    if @review.save
      redirect_to room_path(@review.booking.room.id), notice: '評論發佈成功'
    else
      flash.alert = '評論發佈失敗'
      render :show
    end
  end

  private

  def find_room
    @room = Room.find(params[:room_id])
  end

  def booking_params
    params.require(:booking).permit(:user_id, :room_id, :start_at, :end_at, :price_per_night, :serial, :headcount,:viewed)
  end

  def review_params
    params.require(:review).permit(:room_id ,:booking_id, :guest_rating, :accuracy_rating, :check_in_rating, :cleanliness_rating,
                                   :communication_rating, :location_rating, :value_rating, :comment, :review_to)
  end

  def cancel_unpaid_bookings
    Booking.unpaid.each do |booking|
      booking.cancelled! if booking.created_at + 30 * 60 <= Time.current
    end
  end

  def update_past_bookings
    Booking.paid.each do |booking|
      booking.past! if booking.end_at <= Time.current
    end
  end
end


app/helpers/bookings_helper.rb
# frozen_string_literal: true

module BookingsHelper
  def rating_percentage(value)
    percentage = value / 5.0 * 100
    number_to_percentage(percentage, precision: 0)
  end
    
  def average(column)
    @room.reviews.average(column).floor(1)
  end
    
  def no_review_bookings_count
    Booking.includes(:reviews).where(user_id: current_user.id,state: 2,reviews:{id: nil}).count
  end
end

app/views/bookings/checkout.html.erb
<% content_for(:html_title) { '訂單確認' } %>
<h1>訂單確認</h1>
<div class="flex w-11/12 mx-auto rounded-md shadow-md">
  <div class="w-2/5 py-4 mx-auto text-gray-700 bg-red-100 bg-opacity-50 rounded-md">
    <div class="w-2/3 mx-auto rounded-l-md">
      <div>
        <%= form_with url: bookings_path do %>
          <input type="hidden" name="user_id" value="<%= @user.id %>">
          <input type="hidden" name="room_id" value="<%= @room.id %>">
          <input type="hidden" name="room_price" value="<%= @room.price %>">
          <input type="hidden" name="start_at" value="<%= Time.now.to_date %>">
          <input type="hidden" name="end_at" value="<%= 3.days.after.to_date %>">
          <button>付款</button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="w-3/5 bg-cover rounded-r-md">
    <% @room.photos.reverse.each do |photo| %>
      <div>
        <%= image_tag photo.variant(resize: '300x300^') %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/confirm.html.erb
<% content_for(:html_title) { '付款完成' } %>
<h1>付款完成</h1>

app/views/bookings/index.html.erb
<% content_for(:html_title) { '旅程' } %>
<section class="flex flex-col w-full gap-5 px-2 mx-auto mb-10 text-gray-700 sm:px-0 sm:w-11/12 md:w-10/12 xxl:w-9/12 lg:max-w-1024">
  <h2 class="ml-5 text-2xl font-bold">旅程</h2>
  <div data-controller="booking-list-expand" class="flex flex-col justify-center">
    <% if current_user.bookings.paid.not_due.present? %>
      <div>
        <div class="flex w-full gap-5 overflow-hidden border border-gray-200 md:flex-start rounded-xl">
          <div class="flex flex-col items-center w-full m-3 sm:w-fit md:items-start md:m-8 xl:col-span-1">
            <i class="py-5 text-4xl gradient-text fa-solid fa-suitcase-rolling"></i>
            <span class="my-1 text-lg font-bold"><%=@first_booking.start_at %> - <%=@first_booking.end_at %> 的旅程</span>
            <span class="mb-5 text-sm text-gray-500">共<%=(@first_booking.end_at - @first_booking.start_at).to_i%>晚</span>
            <button class="w-full py-3 font-bold text-white rounded-lg bg-color-main md:w-28"><%= link_to '訂單資訊', booking_path(@first_booking.id)%></button>
          </div>
          <div class="hidden w-full rounded-r-xl sm:block">
            <% if Room.find(@first_booking.room_id).photos.attach %>
              <%= image_tag Room.find(@first_booking.room_id).photos.first, class:"object-cover w-full h-72"%>
            <% end %>
          </div>
        </div>
      </div>
      <% if current_user.bookings.paid.not_due.size > 1 %>
        <button class="flex justify-center w-full py-2 font-bold text-gray-400 bg-gray-200 rounded" data-action="click->booking-list-expand#expand" data-booking-list-expand-target="expandBtn"><i class="fa-solid fa-caret-down"></i> 更多已預定旅程</button>
        <div class="hidden" data-booking-list-expand-target="listToExpand">
          <% current_user.bookings.where(state: "paid").order(start_at: :ASC)[1..current_user.bookings.size].each do |booking| %>
            <div class="grid w-full grid-cols-3 p-3 mb-8 border border-gray-200 md:flex-start md:p-0 rounded-xl">
              <div class="flex flex-col items-center w-full col-span-2 m-3 md:items-start md:m-8 xl:col-span-1">
                <div class="py-5">
                  <i class="text-4xl gradient-text fa-solid fa-suitcase-rolling"></i>
                </div>
                <span class="my-1 text-lg font-bold"><%=booking.start_at %> - <%=booking.end_at %> 的旅程</span>
                <span class="mb-5 text-sm text-gray-500">共<%=(booking.end_at - booking.start_at).to_i%>晚</span>
                <button class="w-full py-3 font-bold text-white rounded-lg bg-color-main md:w-28">
                  <%= link_to '訂單資訊', booking_path(booking)%>
                </button>
              </div>
              <div class="col-span-2 rounded-r-xl md:block xl:2/5">
                <% if Room.find(@first_booking.room_id).photos.attach%>
                  <%= image_tag Room.find(booking.room_id).photos.first, class:"object-cover rounded-r-xl w-full h-72"%>
                <%end%>
              </div>
            </div>
          <% end %>
        </div>
        <button class="justify-center hidden w-full py-2 font-bold text-gray-400 bg-gray-200 rounded" data-action="click->booking-list-expand#collapse" data-booking-list-expand-target="collapseBtn"><i class="fa-solid fa-caret-up"></i> 收回</button>
      <% end %>
    <% else %>
      <div class="flex justify-center w-full mb-8 border border-gray-200 md:flex-start md:p-0 rounded-xl">
        <div class="flex flex-col items-center w-full m-3 md:items-start md:m-8 xl:w-1/3">
          <div class="py-5">
            <i class="text-4xl gradient-text fa-solid fa-hands-clapping fa-flip-horizontal"></i>
          </div>
          <span class="my-1 text-lg font-bold">還沒預訂任何旅程！</span>
          <span class="mb-5 text-sm text-gray-500">該拿出行李箱，開始規劃下一趟冒險之旅了</span>
          <a  href="<%= root_path %>"  class="btn w-fit">開始搜尋</a>
        </div>
        <div class="hidden rounded-r-xl md:block xl:2/5)">
          <img class="object-cover h-full rounded-r-xl" style="aspect-ratio: 4 / 1" src="https://a0.muscache.com/im/pictures/d727f355-3f10-44b5-9750-d1efca2438fc.jpg?im_w=1200" alt="">
        </div>
      </div>
    <% end %>
  </div>
  <% if @past_bookings.present? %>
    <div>
      <h2 class="mb-6 text-2xl font-bold">你去過的地方</h2>
      <div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <% @past_bookings.each do |booking| %>
          <a href="<%=booking_path(booking)%>" class="flex overflow-hidden bg-white border rounded-md shadow-lg max-h-min">
            <div class="w-28">
              <%= image_tag Room.find(booking.room_id)&.photos.first, class:"object-cover h-full w-full "%>
            </div>
            <div class="flex flex-col justify-start flex-shrink-0 gap-3 p-3 ">
              <h3 class="text-lg font-bold"><%=Room.find(booking.room_id).address%></h3>
              <span class="text-sm text-gray-500">房東：<%=User.find(Room.find(booking.room_id).user_id).name%></span>
              <span class="text-sm text-gray-500"><%=booking.start_at%> - <%=booking.end_at%></span>
            </div>
          </a>
        <% end %>
      </div>
    </div>
  <%end%>
</section>

app/views/bookings/new.html.erb
<% content_for(:html_title) { '確認並付款' } %>
<section  data-controller="payment" 
          data-price="<%= @room.price * @nights %>"
          data-id="<%= @room.id %>"
          data-sttime="<%= @booking.start_at %>"
          data-endtime="<%= @booking.end_at %>"
          class="relative z-auto flex flex-col w-full gap-5 px-5 mx-auto mb-10 text-gray-700 sm:w-11/12 sm:z-0 sm:px-0 lg:max-w-1366">
  <!--Title-->
  <button class="sticky left-0 flex items-center justify-center w-full h-20 col-span-5 gap-2 text-center bg-white sm:relative sm:justify-start">
    <h1 class="h2">確認並付款</h1>
    <div class='flex items-center justify-center px-2 py-2'>
      <i class="fa-solid fa-chevron-right"></i>
    </div>
  </button>
  <!--Booking_info-->
  <div class="relative flex flex-col justify-between gap-5 sm:flex-row">
    <div class="flex flex-col content-between gap-5">
      <!--Room_info_sm-->
      <div class="block overflow-hidden border rounded-md shadow-md sm:hidden">
        <div class="flex gap-5">
          <%= image_tag @room.photos.first, class:"aspect-ratio object-cover w-1/2"%>
          <div class="flex flex-col justify-between gap-2 py-5 ">
            <div class="flex flex-col gap-2">
              <span class="font-medium text-gray-500 ">
                <%=Room.human_enum_name(:home_type, @room.home_type)%>
                <span>中的</span>
                <%=Room.human_enum_name(:room_type, @room.room_type)%></span>
              <span class="font-medium "><%=@room_intro%></span>
            </div>
            <% if @room.reviews.any?%>
              <div class="flex gap-2">
                <div class="flex items-center gap-1 font-medium text-md">
                  <div class="flex items-center gap-1">
                    <i class="pb-0.5 text-sm fa-solid fa-star"></i>
                    <span><%= ((average(:value_rating) + average(:accuracy_rating) +  average(:check_in_rating) + average(:cleanliness_rating) + average(:communication_rating) + average(:value_rating))/6).floor(1) %></span>
                  </div>
                  <span>．</span>
                  <p class="flex gap-1"><%= @room.reviews.count%>
                    <span>則評價</span>
                  </p>
                </div>
              </div>
            <%end%>
          </div>
        </div>
      </div>
      <!-- date_and_headcount -->
      <div class="flex flex-col gap-5">
        <h2 class="text-xl font-bold ">你的旅程</h2>
        <div class="flex justify-between date">
          <div>
            <h3 class="mb-1 font-bold">日期</h3>
            <span><%=params[:start_at].to_date%>至<%=params[:end_at].to_date%></span>
          </div>
          <a class="hidden font-bold underline" href="#">編輯</a>
        </div>
        <div class="flex justify-between headcount">
          <div>
            <h3 class="mb-1 font-bold">房客人數</h3>
            <span><%=params[:headcount]%>位房客</span>
          </div>
          <a class="hidden font-bold underline" href="#">編輯</a>
        </div>
      </div>
      <!-- pay_way -->
      <div class="">
        <h2 class="my-5 text-xl font-bold">選擇分期付款</h2>
        <div>
          <div class="p-3 border-2 border-gray-600 rounded-lg">
            <div class="flex justify-between">
              <span class="font-bold">全額支付</span>
              <div class="flex content-center">
                <span class="font-bold"><%=number_to_currency(@room.price * @nights, precision: 0)%></span>
                <input class="w-5 h-6 ml-2 bg-black" type="radio" name="pay-way" checked/>
              </div>
            </div>
            <p class="text-gray-400">立即支付總額，一切就大功告成了。</p>
          </div>
          <div class="hidden p-3 border-2 border-t-0 border-gray-300 rounded-b-lg">
            <div class="flex justify-between">
              <span class="font-bold">立即支付部分費用，之後再付清餘額</span>
              <div class="flex content-center">
                <span class="font-bold">$462</span>
                <input class="w-5 h-6 ml-2 bg-black" type="radio" name="pay-way"/>
              </div>
            </div>
            <div>
              <p class="text-gray-400">
                現在支付$462.00，剩餘款項 ($1,848.00)
                將於2023年1月4日透過相同的付款方式自動扣款。 沒有額外費用。
              </p>
              <a href="#">更多資訊</a>
            </div>
          </div>
        </div>
      </div>
      <!-- price_detail -->
      <div class="md:hidden">
        <h2 class="mb-4 text-xl font-bold">價格詳情</h2>
        <div class="flex justify-between mb-2">
          <span class="flex justify-between">$<%=@room.price%>TWD x <%=params[:nights]%>晚</span>
          <span>$<%=@room.price * @nights%> TWD</span>
        </div>
        <div class="flex justify-between mb-3">
          <span>服務費</span>
          <span>$0 TWD</span>
        </div>
        <div class="flex justify-between mb-3">
          <span>稅費</span>
          <span>$110 TWD</span>
        </div>
        <div class="flex justify-between mb-3 font-bold">
          <span>總價<a href="#" class="underline">(TWD)</a></span>
          <span>$<%=@room.price * @nights%></span>
        </div>
        <a href="#" class="flex justify-end font-bold underline">更多資訊</a>
      </div>
      <!-- pay_with -->
      <div class="">
        <h2 class="my-5 text-xl font-bold">付款方式：</h2>
        <div class="flex items-center justify-between p-3 mb-5 border-2 border-gray-600 rounded-lg">
          <label for="ebpay">
            <img class="w-28" src="https://scontent.ftpe7-2.fna.fbcdn.net/v/t1.18169-9/18813863_1341299215906701_2921742938832542248_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=9267fe&_nc_ohc=4-yTxDc0dioAX_863tI&_nc_ht=scontent.ftpe7-2.fna&oh=00_AfAdcWH3S1uxl_Fp_1KLogPUASu0jllOkLZnWFJWaxJkPQ&oe=63CD01DA" alt=""/>
          </label>
          <input data-action="click->payment#btneb" class="w-5 h-6 bg-gray-400" type="radio" name="pay-with" id="ebpay" checked/>
        </div>
        <div 
        class="flex items-center justify-between p-3 mb-5 border-2 border-gray-600 rounded-lg">
          <label for="linepay">
            <img class="w-28" src="https://www.new-thing.org/sites/www.new-thing.org/files/field/image/logo_0.jpg" alt=""/>
          </label>
          <input data-action="click->payment#btnline" 
          data-payment-target="position"
          class="w-5 h-6 bg-gray-400" type="radio" name="pay-with" id="linepay" checked/>
        </div>
      </div>
      <div class="flex flex-col gap-5 p-5">
        <div class="flex flex-col gap-3">
          <h2 class="text-xl font-bold ">退訂政策</h2>
          <span><em class="not-italic font-bold">在 1月12日前可以免費取消。</em> 在這之後，該筆預訂則無法退款。</span>
          <a href="#" class="font-bold underline">了解詳情</a>
        </div>
        <div class="flex flex-col gap-2">
          <h2 class="text-xl font-bold ">基本守則</h2>
          <span>我們請房客記得遵守幾個簡單的事項，當個優質的房客。</span>
          <span>遵守《房屋守則》</span>
          <span>請把房源當成自己的家來愛護</span>
        </ul>
      </div>
      <!-- policy_agree -->
      <div class="text-xs">
        點選以下按鈕即表示本人同意
        <a class="font-bold underline">房東的《房屋守則》</a>、
        <a class="font-bold underline">《房客基本守則》</a>、
        <a class="font-bold underline">《重新預訂和退款政策》</a>
        ，且允許 Airbnb 在我應負責賠償損壞時，可以
        <a class="font-bold underline">向我的付款方式扣款</a>
        。
      </div>
    </div>
    <div data-payment-target="linePay" class="flex justify-end mb-5">
      <%= form_with(model: @booking) do |booking| %>
        <%= booking.hidden_field :room_id, value: params[:room_id] %>
        <%= booking.hidden_field :user_id, value: current_user.id%>
        <%= booking.hidden_field :start_at, value: params[:start_at].to_date %>
        <%= booking.hidden_field :end_at, value: params[:end_at].to_date %>
        <%= booking.hidden_field :price_per_night, value: @room.price %>
        <%= booking.hidden_field :headcount, value: params[:headcount] %>
        <div class="flex justify-end gap-5">
          <button class="flex justify-center btn-cancel text-md whitespace-nowrap confirm md:w-40">
            <%=link_to '回上一頁重新輸入', room_path(@room)%>
          </button>
          <button class="flex justify-center ml-3 btn confirm md:w-40">
            <%= booking.submit '確認並付款',class:"cursor-pointer"%>
          </button>
        </div>
      <% end %>
    </div>
    <!-- ebpay_form -->
    <div data-payment-target="ebPay" class="justify-end hidden mb-5 ">
      <%= form_with url: "https://ccore.spgateway.com/MPG/mpg_gateway" do |booking| %>
        <div class="flex justify-end gap-5">
          <button class="flex justify-center btn-cancel text-md whitespace-nowrap md:w-40">
            <%=link_to '回上一頁重新輸入', room_path(@room)%>
          </button>
          <button class="flex justify-center ml-3 btn md:w-40">
            <%= booking.submit '確認並付款',class:"cursor-pointer"%>
          </button>
        </div>
        <input type="hidden" id="MerchantID" name="MerchantID" value="MS146289298" data-payment-target="MerchantID">
        <input type="hidden" id="TradeInfo" name="TradeInfo" value="<%= @form_TradeInfo %>"
        data-payment-target="TradeInfo">
        <input type="hidden" id="TradeSha" name="TradeSha" value="<%= @form_TradeSha %>"
        data-payment-target="TradeSha">
        <input type="hidden" id="RespondType" name="RespondType" value="JSON"
        data-payment-target="RespondType">
        <input type="hidden" id="TimeStamp" name="TimeStamp" value="1671860988"
        data-payment-target="TimeStamp">
        <input type="hidden" id="Version" name="Version" value="1.6"
        data-payment-target="Version">
        <input type="hidden" id="MerchantOrderNo" name="MerchantOrderNo" value="<%= @form_serial %>"
        data-payment-target="MerchantOrderNo">
        <input type="hidden" id="Amt" name="MerchantOprice_per_night" value=""
        data-payment-target="Amt">
        <input type="hidden" id="ItemDesc" name="ItemDesc" value="TEST"
        data-payment-target="ItemDesc">
        <input type="hidden" id="Email" name="Email" value="<%= current_user.email %>"
        data-payment-target="Email">
        <input type="hidden" id="LoginType" name="LoginType" value="是否需要登入會員"
        data-payment-target="LoginType">
      <% end %>
    </div>
  </div>
  <!-- booking_info_card  -->
  <div class="relative hidden w-1/2 max-w-450 md:block">
    <div class="sticky flex flex-col gap-5 p-5 bg-white border shadow-md top-20 rounded-xl">
      <div class="flex flex-col gap-5">
        <div class="flex flex-col gap-3 border-gray-100">
          <%= image_tag @room.photos&.first, class:"object-cover w-full lg:w-full h-32 rounded-md" %>
          <div class="flex flex-col justify-between gap-3 room-info">
            <div class="flex flex-row gap-3">
              <span class="text-xs text-gray-500"><%=Room.human_enum_name(:home_type, @room.home_type)%>中的<%=Room.human_enum_name(:room_type, @room.room_type)%></span>
              <span class="inline-block text-sm"><%=@room_intro%></span>
            </div>
            <% if @room.reviews.any?%>
              <div class="flex gap-2">
                <div class="flex items-center gap-1 font-medium text-md">
                  <div class="flex items-center gap-1">
                    <i class="pb-0.5 text-sm fa-solid fa-star"></i>
                    <span><%= ((average(:value_rating) + average(:accuracy_rating) +  average(:check_in_rating) + average(:cleanliness_rating) + average(:communication_rating) + average(:value_rating))/6).floor(1) %></span>
                  </div>
                  <span>．</span>
                  <p class="flex gap-1"><%= @room.reviews.count%>
                    <span>則評價</span>
                  </p>
                </div>
              </div>
            <%end%>
          </div>
        </div>
        <div class="flex flex-wrap mb-5 text-sm border-gray-100">
          <p class="font-bold">
            <span class="gradient-text">Roomit</span><span>cover </span>
          </p>
          <span>為你的預定提供保障</span>
        </div>
      </div>
      <div class= "flex flex-col gap-3 border-gray-100 ">
        <h2 class="text-xl font-bold ">價格詳情</h2>
        <p class="flex items-center text-sm"><%=number_to_currency(@room.price, unit: 'TWD', precision: 0)%>
          <span>x</span>
          <span><%=@nights%>晚</span>
        </p>
        <div class="flex flex-wrap justify-between font-bold">
          <span>總價<a class="underline">(TWD)</a></span>
          <span><%=number_to_currency(@room.price * @nights, precision: 0)%></span>
        </div>
        <a href="#" class="flex justify-end font-bold underline">更多資訊</a>
      </div>
    </div>
  </div>
</div>
</section>