config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "rooms#index"
  get 'search/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: { sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks",
                            passwords: "users/passwords", registrations: "users/registrations", confirmations: "users/confirmations", mailer: "users/mailer", unlocks: "users/unlocks" }
  resources :rooms do
    delete "/photos/:photo_id" => "rooms#destroy_photo", as: :destroy_photo, on: :member
    collection do
      get "manage"
      get "wish_list_rooms"
    end
    member do
      patch :wish_list
    end
  end

  resources :bookings, only: %i[create show new index]  do
    member do
      get "confirm"
      get "cancel"
      post "create_review"
    end
      collection do
      get 'ebpay'
      post 'ebpaid'
    end
  end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  has_many :bookings
  has_many :guests, through: :bookings, source: :users
  has_many :wish_list_rooms
  has_many :reviews
  has_many :liked_users, through: :wish_list_rooms, source: :user

  has_many_attached :photos

  validates :home_type, :room_type, :max_occupancy, :bedrooms, :bathrooms, :summary, :address, :price,
            :checkin_start_at, :checkin_end_at, :checkout_time, presence: true
  validate :checkin_time_more_then_3_hours

  enum home_type: {
    'boutique_hotel' => 0,
    'hotel' => 1,
    'bed_and_breakfast' => 2,
    'aparthotel' => 3,
    'hostel' => 4,
    'minsu' => 5,
    'nature_lodge' => 6,
    'resort' => 7,
    'ryokan' => 8
  }

  enum room_type: { 'entire_place' => 0, 'private_rooms' => 1, 'hotel_rooms' => 2, 'shared_rooms' => 3 }

  enum checkin_start_at: { "11:00": 11, "12:00": 12, "13:00": 13, "14:00": 14, "15:00": 15, "16:00": 16, "17:00": 17, "18:00": 18 },
       _prefix: :checkin_start_at
  enum checkin_end_at: { "14:00": 14, "15:00": 15, "16:00": 16, "17:00": 17, "18:00": 18, "19:00": 19, "20:00": 20, "21:00": 21, "22:00": 22, "23:00": 23, "半夜": 24 },
       _prefix: :checkin_end_at
  enum checkout_time: { "11:00": 11, "12:00": 12, "13:00": 13, "14:00": 14, "15:00": 15, "16:00": 16 },
       _prefix: :checkout_time

  private
  
  def checkin_time_more_then_3_hours
    return unless Room.checkin_end_ats[checkin_end_at] - Room.checkin_start_ats[checkin_start_at] < 3

    errors.add(:checkin_end_at, 'checkin time should be more than 3 hours')
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  require 'mini_magick'

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :find_hosted_rooms, only: [:manage]
  before_action :find_all_rooms, only: [:index]
  before_action :find_room, only: %i[show wish_list]
  before_action :find_hosted_room, only: %i[edit update destroy destroy_photo]
  before_action :should_compelete_user_info, only: [:new]

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.new(room_params)

    @geocoding_obj = GoogGeocodingApi.new(@room.address)
    @coordinates = @geocoding_obj.get_response

    if @coordinates.nil?
      flash.alert = '請輸入有效的地址'
      render :new
    else
      @room.lat = @geocoding_obj.get_lat(@coordinates)
      @room.lng = @geocoding_obj.get_lng(@coordinates)

      if @room.save
        redirect_to manage_rooms_path, notice: '新增成功'
      else
        flash.alert = '新增失敗'
        render :new
      end
    end
  end

  def show
    @bookings = Booking.where(room_id: @room.id)
    @disable_dates = disable_dates(@room).flatten

    @places_obj = GoogPlacesApi.new("#{@room.lat}%2C#{@room.lng}")
    @tourist_attractions = @places_obj.get_tourist_attractions
    @restaurants = @places_obj.get_restaurants
    @bars = @places_obj.get_bars
  end

  def edit; end

  def update
    if params[:room][:photos].present?
      params[:room][:photos].each do |photo|
        @room.photos.attach(photo)
      end
    end

    @geocoding_obj = GoogGeocodingApi.new(params[:room][:address])
    @coordinates = @geocoding_obj.get_response

    if @coordinates.nil?
      flash.alert = '請輸入有效的地址'
      render :edit
    else
      if @room.update(room_params_without_photos)
        @room.update(
          lat: @geocoding_obj.get_lat(@coordinates),
          lng: @geocoding_obj.get_lng(@coordinates)
        )
  
        redirect_to manage_rooms_path, notice: '更新成功'
      else
        flash.alert = '更新失敗'
        render :edit
      end
    end
  end

  def destroy
    @room.destroy
    redirect_to manage_rooms_path, notice: '已刪除'
  end

  def destroy_photo
    @room.photos.find(params[:photo_id]).purge_later
    respond_to do |format|
      format.html { render :edit, notice: '圖片已刪除' }
      format.json { head :no_content }
    end
  end

  def manage
    @bookings_query = current_user.bookings_to_hosted_rooms.where(state: [2, 4]).includes([:room]).includes([:user]).ransack(params[:q])
    @bookings = @bookings_query.result.order(:created_at).reverse_order


    monthly_income_data_query = <<-SQL
    SELECT  b.end_at, SUM(b.price_per_night * (b.end_at - b.start_at)) 
    FROM rooms AS r
    LEFT JOIN bookings AS b
      ON r.id = b.room_id
    WHERE r.user_id = #{current_user.id}
      AND b.id IS NOT NULL
      AND b.start_at >= DATE_TRUNC('month', NOW())::DATE
      AND b.end_at <= (DATE_TRUNC('month', NOW()::DATE) + INTERVAL '1 month' - INTERVAL '1 day')::DATE
      AND b.state IN (2, 4)
    GROUP BY b.end_at;
    SQL
    monthly_paid_income_query = <<-SQL
      SELECT  SUM(b.price_per_night * (b.end_at - b.start_at)) 
      FROM rooms AS r
      LEFT JOIN bookings AS b
        ON r.id = b.room_id
      WHERE r.user_id = #{current_user.id}
        AND b.id IS NOT NULL
        AND b.start_at >= DATE_TRUNC('month', NOW())::DATE
        AND b.end_at <= (DATE_TRUNC('month', NOW()::DATE) + INTERVAL '1 month' - INTERVAL '1 day')::DATE
        AND b.state = 2;
    SQL
    monthly_past_income_query = <<-SQL
      SELECT  SUM(b.price_per_night * (b.end_at - b.start_at)) 
      FROM rooms AS r
      LEFT JOIN bookings AS b
        ON r.id = b.room_id
      WHERE r.user_id = #{current_user.id}
        AND b.id IS NOT NULL
        AND b.start_at >= DATE_TRUNC('month', NOW())::DATE
        AND b.end_at <= (DATE_TRUNC('month', NOW()::DATE) + INTERVAL '1 month' - INTERVAL '1 day')::DATE
        AND b.state = 4;
    SQL
    
    @monthly_income_data = ActiveRecord::Base.connection.execute(monthly_income_data_query).values

    @monthly_paid_income_result = ActiveRecord::Base.connection.execute(monthly_paid_income_query).values.flatten.first
    @monthly_paid_income = @monthly_paid_income_result.nil? ? 0 : @monthly_paid_income_result
    
    @monthly_past_income_result = ActiveRecord::Base.connection.execute(monthly_past_income_query).values.flatten.first
    @monthly_past_income = @monthly_past_income_result.nil? ? 0 : @monthly_past_income_result
      # dashbord end
  end

  def wish_list
    if current_user.liked_wish_list_rooms.include?(@room)
      current_user.liked_wish_list_rooms.delete(@room)
      render json: { status: 'unliked' }
    else
      current_user.liked_wish_list_rooms << (@room)
      render json: { status: 'liked' }
    end
  end

  def wish_list_rooms
    @rooms = current_user.liked_wish_list_rooms.includes(:reviews,:photos_attachments)
    @photos = current_user.liked_wish_list_rooms.includes([:photos_attachments])&.first&.photos
    @data = @rooms.select(:id, :lat, :lng)
  end

  private
  
  def find_room
    @room = Room.includes(:photos_attachments,:reviews,photos_attachments: :blob).find(params[:id])
  end

  def find_hosted_rooms
    @rooms = current_user.rooms.includes(:photos_attachments,photos_attachments: :blob)
  end

  def find_hosted_room
    @room = current_user.rooms.find(params[:id])
  end

  def find_all_rooms
    @rooms = Room.includes(:photos_attachments, :reviews,photos_attachments: :blob).reverse_order
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :max_occupancy, :bedrooms, :bathrooms, :has_bathtub,
                                 :has_kitchen, :has_air_con, :has_wifi, :summary, :address, :price, :checkin_start_at, :checkin_end_at, :checkout_time, photos: [])
  end

  def room_params_without_photos
    params.require(:room).permit(:home_type, :room_type, :max_occupancy, :bedrooms, :bathrooms, :has_bathtub,
                                 :has_kitchen, :has_air_con, :has_wifi, :summary, :address, :price, :checkin_start_at, :checkin_end_at, :checkout_time)
  end
end

app/helpers/room_helper.rb
# frozen_string_literal: true

module RoomHelper
  def form_submit_text
    if @room.id.present?
      '更新房源資料'
    else
      '發佈房源'
    end
  end

  def equipment_provided
    res = []
    res << 'Wi-Fi' if @room.has_wifi
    res << '廚房' if @room.has_kitchen
    res << '空調' if @room.has_air_con
    res << '浴缸' if @room.has_bathtub
    res
  end

  def to_twd(number)
    number_to_currency( number, negative_format: "(%u%n)",precision:0,unit: "$")
  end

  def bookings_start_to_end(booking)
    if booking.start_at.year == booking.end_at.year
      "#{booking.start_at.strftime('%Y-%m-%d')} ~ #{booking.end_at.strftime('%m-%d')}"
    else
      "#{booking.start_at.strftime('%Y-%m-%d')} ~ #{booking.end_at.strftime('%Y-%m-%d')}"
    end
  end
end

app/views/rooms/edit.html.erb
<% content_for(:html_title) { '更新房源資料' } %>
<div class="w-full px-10 mb-10 text-gray-700 lg:px-56">
  <div class="flex w-full overflow-hidden text-gray-700 border-2 shadow-md rounded-2xl ">
    <div class="w-1/2 px-10 py-5 text-gray-700 bg-white bg-opacity-50 ">
      <div class="flex flex-col gap-5">
        <h1 class="h1">更新房源資料</h1>
        <div>
          <%= render "form", room: @room %>
        </div>
      </div>
    </div>
    <div class="grid w-1/2 grid-cols-2 gap-1 overflow-y-auto bg-cover h-500">
      <% @room.photos.all.each do |photo| %>
        <div class="relative inline-block h-48 border-2">
          <%= image_tag photo, class:"w-full h-full object-cover"%>
          <%= link_to destroy_photo_room_path(@room, photo), method: :delete do %>
            <i class="absolute text-red-400 right-2 top-2 fa-solid fa-circle-xmark"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<main class="w-full px-5 text-gray-700 sm:px-10">
  <div class="grid grid-cols-1 gap-x-7 gap-y-7 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xxl:grid-cols-5 ">
    <% @rooms.each do |room| %>
      <% if room.photos.attached?%>
        <div class="relative card-carousel-container">
          <%= link_to room_path(room) do %>
            <div data-controller="carousel" class="relative flex-grow mx-auto rounded-lg group swiper-container" 
                data-carousel-options-value='{"loop":"true","pagination": { "el": ".swiper-pagination", "dynamicBullets": "true" }, "navigation": {"nextEl": ".swiper-button-next", "prevEl": ".swiper-button-prev"}}'>
              <div class="absolute z-30 flex flex-col justify-between w-full h-full p-3">
                <% if current_user %>
                  <button class="self-end text-2xl text-center transition duration-150 ease-in-out transform hover:scale-125"data-controller="wishList" data-action="click->wishList#wishListState" data-id="<%= room.id%>" data-liked="<%= current_user&.liked_wish_list_rooms&.include?(room) %>">
                    <i data-wishList-target="wishListIcon" class="text-gray-500 opacity-80 fa-solid fa-heart"></i>
                  </button>
                <%end %>
                <div class="flex justify-between w-full my-auto transition duration-500 ease-out opacity-0 group-hover:opacity-100">
                  <div class="flex items-center justify-center w-8 h-8 bg-white rounded-full opacity-70 hover:opacity-100 swiper-button-prev">
                    <i class="text-gray-700 fa-solid fa-chevron-left"></i>
                  </div>
                  <div class="flex items-center justify-center w-8 h-8 bg-white rounded-full opacity-70 hover:opacity-100 swiper-button-next">
                    <i class="text-gray-700 fa-solid fa-chevron-right"></i>
                  </div>
                </div>
              </div>
              <div class="self-center mb-5 swiper-pagination"></div>
              <div class="relative swiper-wrapper">
                <% if room.photos.attached?%>
                  <% room.photos[0..2].each do |photo| %>
                    <div class="swiper-slide">
                      <%=image_tag photo, class:"object-cover w-full aspect-ratio"%>
                    </div>
                  <%end%>
                <%end%>
              </div>
            </div>
            <div class="flex flex-row justify-between p-2 ">
              <div class="flex flex-col gap-0.5 overflow-hidden pr-3 justify-between ">
                <div class="w-full overflow-hidden text-base font-bold whitespace-nowrap"><%=room.address%></div>
                <div class="text-gray-500 "><%=Room.human_enum_name(:room_type, room.room_type)%></div>
                <div class="text-sm text-gray-500 ">
                </div>
                <div class="">
                  <span class="mr-0.5 tracking-wider text-md"><%=number_to_currency(room.price, negative_format: "(%u%n)",precision:0,unit: "$")%></span>
                  <span class="mr-0.5 text-sm">TWD</span>
                  <span class="text-sm">晚</span></div>
              </div>
              <div class="flex items-start justify-end ">
                <%if room.reviews.any?%>
                  <div class="flex items-center gap-1 text-sm font-medium">
                    <div class="flex items-center gap-1">
                      <i class="pb-0.5 text-sm fa-solid fa-star"></i>
                      <span><%= ((
                      room.reviews.average(:value_rating).floor(1)+
                      room.reviews.average(:accuracy_rating).floor(1)+
                      room.reviews.average(:cleanliness_rating).floor(1)+
                      room.reviews.average(:communication_rating).floor(1)+
                      room.reviews.average(:location_rating).floor(1)+
                      room.reviews.average(:value_rating).floor(1))/6).floor(1) %></span>
                    </div>
                  </div>
                <%end%>
              </div>
            </div>
          <% end %>
        </div>
      <%end%>
    <% end %>
  </div>
</main>

app/views/rooms/manage.html.erb
<% content_for(:html_title) { '管理房源' } %>
<div class="flex flex-col w-full gap-5 mx-auto mb-10 text-gray-700 sm:w-11/12 md:w-10/12 xxl:w-9/12 lg:max-w-1366">
  <!-- room_edit -->
  <h1 class="h1">管理房源</h1>
  <div class="relative mb-2 overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 table-fixed">
      <thead class="text-sm text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="w-8/12 px-2 py-5 sm:w-4/12">
            地址
          </th>
          <th scope="col" class="hidden px-2 sm:table-cell sm:w-4/12">
            介紹
          </th>
          <th scope="col" class="w-2/12 px-2 sm:w-2/12">
            價格
          </th>
          <th scope="col" class="w-2/12 px-2 sm:w-2/12">
            選項
          </th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.reverse.each do |room| %>
          <tr class="bg-white border-b ">
            <th scope="row" class="py-5 font-medium text-gray-700">
              <% if room.photos.attached?%>
                <div class="flex"><%=image_tag room.photos.first, class:"rounded-lg w-16 h-16 object-cover mr-3", alt:"room-photo"%>
                  <div class="flex flex-col flex-wrap gap-1 px-2">
                    <%= link_to room.address, room_path(room), class:"block" %>
                    <%= Room.human_enum_name(:home_type, room.home_type) %>
                  </div>
                </div>
              <%end%>
            </th>
            <td class="hidden px-2 sm:table-cell">
              <%= room.summary %>
            </td>
            <td class="px-2">
              <%= to_twd(room.price)%>
            </td>
            <td>
              <div class="flex flex-col items-start gap-2 px-2 sm:items-center sm:flex-row ">
                <button class="flex-shrink-0 px-1 py-1 text-white rounded sm:px-3 sm:py-2 btn w-fit"><%= link_to "編輯", edit_room_path(room) %></button>
                <a href="<%= room_path(room)%>" data-method="DELETE" data-confirm="確定要刪除嗎？">
                  <i class="flex-shrink-0 p-2 fa-regular fa-trash-can btn-delete"></i>
                </a>
              </div>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  <!-- 即將到來的住宿 -->
  <h2 class="h2">住宿列表</h2>
  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 table-fixed">
      <thead class="text-sm text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="w-8/12 px-2 py-5 sm:w-4/12">
            <%= sort_link(@bookings_query, :room_id, '房源') %>
          </th>
          <th scope="col" class="hidden px-2 py-5 sm:block">
            <div class="flex flex-wrap gap-1">
              <p class="w-fit"><%= sort_link(@bookings_query, :start_at, '住宿開始日') %></p>
              <span>~</span>
              <p class="w-fit"><%= sort_link(@bookings_query, :end_at, '結束日') %></p>
            </div>
          </th>
          <th scope="col" class="hidden w-2/12 px-2 sm:table-cell">
            入住者
          </th>
          <th scope="col" class="w-2/12 px-2">
            總價
          </th>
          <th scope="col" class="w-2/12 px-2">
            狀態
          </th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking|%>
          <tr class="border-b">
            <th scope="row" class="py-5 font-medium text-gray-700">
              <%= link_to room_path(booking.room) do %>
                <div class="flex flex-row items-start sm:items-center">
                  <%=image_tag booking.room.photos.first, class:"rounded-lg w-16 h-16 object-cover mr-3", alt:"room-photo"%>
                  <div>
                    <p><%=booking.room.address%></p>
                    <p class="sm:hidden"><%=bookings_start_to_end(booking)%></p>
                  </div>
                </div>
              <% end %>
            </th>
            <td class="hidden px-2 sm:table-cell">
              <%=bookings_start_to_end(booking)%>
            </td>
            <td class="hidden px-2 sm:table-cell">
              <%=booking.user.name%>
              <%#=image_tag booking.user.avatar, class:"rounded-full w-16 h-16 object-cover", alt:"guest-avatar" %>
            </td>
            <td class="px-2">
              <%=to_twd(booking.price_per_night * (booking.end_at - booking.start_at).to_i)%>
            </td>
            <td class="px-2 text-xs sm:text-sm">
              <%if booking.past?%>
                <span>已完成</span>
                <!-- 
                <button class="flex-shrink-0 px-1 py-1 my-1 text-white rounded btn w-fit sm:px-3 sm:py-2">評論房客</#button>
                -->
              <%elsif booking.start_at < Time.current%>
                <span class='bold'>進行中</span>
              <%else%>
                <span>即將到來</span>
              <%end%>
            </td>
          </tr>
          <div class="flex gap-1 font-bold h3">
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="flex flex-col gap-5">
    <h2 class="h2">本月預定收入</h2>
    <div class="flex text-sm ">
      <div class="flex flex-col w-40 gap-1">
        <h3 class="">本月可提領收入：</h3>
        <h3 class="">本月預期收入：</h3>
        <h3 class="font-bold ">本月總預定收入：</h3>
      </div>
      <div class="flex flex-col justify-end gap-1">
        <span><%= to_twd(@monthly_past_income) %></span>
        <span class="underline"><%= to_twd(@monthly_paid_income) %></span>
        <span class="font-bold "><%= to_twd(@monthly_past_income + @monthly_paid_income)%></span>
      </div>
    </div>
    <div class="mb-8">
      <%# dashboard will be here %>
      <%= line_chart @monthly_income_data, 
        xmin: Date.today.beginning_of_month, xmax: Date.today.end_of_month,
        ytitle: '收入', loading: 'Loading...', empty: 'No data', prefix: '$', 
        colors: ["#ed64a6"] %>
    </div>
  </div>
  <!-- 未來收入 -->

app/views/rooms/new.html.erb
<% content_for(:html_title) { '新增房源' } %>
<section class="w-full mx-auto mb-10 text-gray-700 sm:w-11/12 md:w-10/12 xxl:w-9/12 lg:max-w-1024 ">
  <div class="flex w-full overflow-hidden text-gray-700 border shadow-md rounded-2xl">
    <div class="w-full p-5 text-gray-700 bg-white ">
      <div class="flex flex-col gap-5">
        <h1 class="h1">新增房源</h1>
        <div>
          <%= render "form", room: @room %>
        </div>
      </div>
    </div>
    <div class="hidden w-64 bg-cover xl:block bg-color-main ">
    </div>
  </div>
</section>

app/views/rooms/wish_list_rooms.html.erb
<% content_for(:html_title) { '心願單' } %>
<section class="flex w-full bg-white h-full-with-nav ">
  <div class="flex flex-col w-full gap-3 p-5 bg-white max-w-none md:max-w-500">
    <div class="flex items-center justify-between px-2">
      <%= link_to url_for(:back),class:"p-2 block font-bold text-gray-400 bg-white w-fit hover:text-gray-500" do%>
        <i class="fa-solid fa-chevron-left"></i>返回
      <%end%>
      <h2 class="text-center text-gray-700 h2">心願單</h2>
    </div>
    <div class="flex flex-col items-center justify-center w-full h-full">
      <%if current_user.liked_wish_list_rooms.present?%>
        <div class="grid w-full h-auto grid-cols-1 gap-3 p-2 mx-auto overflow-y-scroll border md:h-800 sm:grid-cols-2 md:grid-cols-1 h-fit">
          <% current_user.liked_wish_list_rooms.each do |room| %>
            <a href="<%=room_path(room.id)%>" class="flex flex-col items-center gap-2 p-3 bg-white border shadow-md md:max-h-min md:flex-row md:items-start rounded-xl">
              <!-- card_img -->
              <!-- card_img -->
              <div class="relative w-full md:w-1/3 ">
                <div  class="relative flex-grow mx-auto rounded-lg group swiper-container">
                  <div class="absolute z-30 flex flex-col justify-between w-full h-full p-3">
                    <% if current_user %>
                      <button class="self-end text-2xl text-center transition duration-150 ease-in-out transform hover:scale-125"data-controller="wishList" data-action="click->wishList#wishListState" data-id="<%= room.id%>" data-liked="<%= current_user&.liked_wish_list_rooms&.include?(room) %>">
                        <i data-wishList-target="wishListIcon" class="text-gray-500 opacity-80 fa-solid fa-heart"></i>
                      </button>
                    <%end %>
                  </div>
                  <div class="relative">
                    <% if room.photos.attached?%>
                      <%=image_tag room.photos.first, class:"object-cover w-full aspect-ratio"%>
                    <%end %>
                  </div>
                </div>
              </div>
              <!-- card_text -->
              <div class="flex w-full gap-5 p-2 md:w-2/3 ">
                <div class="flex flex-row justify-between w-full gap-1 overflow-hidden md:flex-col">
                  <div class="flex flex-col justify-start gap-1">
                    <div class="w-full overflow-hidden text-base font-bold whitespace-nowrap"><%=room.address%></div>
                    <div class="text-gray-500"><%=Room.human_enum_name(:home_type, room.home_type) %>的<%=Room.human_enum_name(:room_type, room.room_type)%>
                    </div>
                    <div class="flex gap-0.5 items-center">
                      <span class="tracking-wider text-md"><%=number_to_currency(room.price, negative_format: "(%u%n)",precision:0,unit: "$")%></span>
                      <span class="text-sm ">TWD</span>
                      <span class="text-sm">晚</span>
                    </div>
                  </div>
                  <% if room.reviews.any?%>
                    <div class="flex items-start ">
                      <div class="flex gap-1 text-sm font-medium items-star">
                        <div class="flex items-center gap-1">
                          <i class="pb-0.5 text-sm fa-solid fa-star"></i>
                          <span><%= ((
                      room.reviews.average(:value_rating).floor(1)+
                      room.reviews.average(:accuracy_rating).floor(1)+
                      room.reviews.average(:cleanliness_rating).floor(1)+
                      room.reviews.average(:communication_rating).floor(1)+
                      room.reviews.average(:location_rating).floor(1)+
                      room.reviews.average(:value_rating).floor(1))/6).floor(1) %></span>
                        </div>
                      </div>
                    </div>
                  <%end%>
                </div>
              </div>
            </a>
          <%end%>
        </div>
      <%else%>
        <div class="flex flex-col items-center w-full gap-5 ">
          <i class="text-4xl fa-solid fa-magnifying-glass gradient-text fa-flip-horizontal"></i>
          <div class="flex flex-col items-center justify-center gap-2">
            <span class="text-lg font-bold">您還沒加入任何心願房源！</span>
            <span class="text-sm text-gray-500 ">該拿出行李箱，開始規劃下一趟冒險之旅了</span>
          </div>
          <a  href="<%= root_path %>"  class="font-bold btn w-fit">開始探索</a>
        </div>
      <%end%>
    </div>
  </div>
  <div class="hidden w-full h-full md:block">
    <%= react_component('GoogleWLMap', 
      { api_key: ENV['GOOG_MAPS_API_KEY'], data: @data })%>
  </div>
</section>