config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "rooms#index"
  get 'search/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: { sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks",
                            passwords: "users/passwords", registrations: "users/registrations", confirmations: "users/confirmations", mailer: "users/mailer", unlocks: "users/unlocks" }
  resources :rooms do
    delete "/photos/:photo_id" => "rooms#destroy_photo", as: :destroy_photo, on: :member
    collection do
      get "manage"
      get "wish_list_rooms"
    end
    member do
      patch :wish_list
    end
  end

  resources :bookings, only: %i[create show new index]  do
    member do
      get "confirm"
      get "cancel"
      post "create_review"
    end
      collection do
      get 'ebpay'
      post 'ebpaid'
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
  def index
      @review = Review.all
    end
    
    def new
      @review = Review.new
    end

    def create
      @review = Review.new(review_params)

      if @review.save
        redirect_to review_path, notice: '已完成評價'
      else
        flash[:alert] = '未完成評價'
        render :new
      end
    end

    def edit
    end

    def update
      if @review.update(reviews_params)
        redirect_to root_path, notice: '已完成更改'
      else
        flash alert: '請重新編輯'
        render :edit
      end
    end

    def destroy
      @review.destroy
      redirect_to root_path, noice: '評價已刪除'
    end

  private

  def find_review
    @reviews = Review.find(params[:id])
  end
     
  def review_params
    params.require(:review).permit(:comment, :user_id, :room_id, :rating, :deleted_at, :state)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<h1>編輯評價</h1>

<%= render "form", reviews: @review %>

<br />
<%=link_to '回評價頁面', reviews_path %>

app/views/reviews/index.html.erb
<h1>所有評價</h1>

<%= link_to "新增評價", new_review_path %>

<% @review.each do |review| %>
  <li>
    <%= link_to "編輯", edit_review_path(review) %>
    <%= link_to "刪除", review_path(review), method: "delete", data: {confirm: "確定嗎"} %>
  </li>
<% end %>

app/views/reviews/new.html.erb
<h1>新增評價</h1>
<%= form_with(model: @review, url: reviews_path, method: "post") do |f| %>
<div>
  <%= f.label :comment, "留言" %>
  <%= f.text_area :comment %>
</div>
<div>
  <%= f.label :rating, "評價" %>
  <%= f.number_field :rating %>
</div>
<div>
  <%= f.label :reviews_date, "留言日期" %>
  <%= f.date_field :reviews_date %>
</div>

  <button class="border-solid border-2 bg-pink-300 ring-offset-4 rounded-full py-1 px-4 hover:bg-green-200">    
    <%= f.submit %></button>  
<% end %>

<br />
<%=link_to '回評價頁面', reviews_path %>